// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import ReactTextareaAutosize from "react-textarea-autosize";

function truncateString(s) {
  if (s.length > 30) {
    return s.slice(0, 27).trimEnd() + "...";
  } else {
    return s;
  }
}

function AdditionText(props) {
  var todoRelation = props.todoRelation;
  var todo = todoRelation.self;
  var additionalTextRef = React.useRef(null);
  var match = Common.useDebounce(Caml_option.nullable_to_opt(todo.additional_text), (function (v) {
          Core__Option.mapOr(v, undefined, (function (v_) {
                  Common.setTodoAdditionalText(todo.id, v_);
                }));
        }), 1000);
  var setAdditionalText = match[1];
  React.useEffect((function () {
          if (Caml_obj.notequal(Caml_option.nullable_to_opt(additionalTextRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
            setAdditionalText(function (param) {
                  return Caml_option.nullable_to_opt(todo.additional_text);
                });
          }
          
        }), [todo.additional_text]);
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(ReactTextareaAutosize, {
                    ref: Caml_option.some(additionalTextRef),
                    className: ["placeholder:text-[var(--t5)] text-sm flex-1 border-none text-[var(--t10)] w-full outline-none \n          focus:ring-0 font-medium"].join(" "),
                    id: "id-display-title",
                    style: {
                      resize: "none"
                    },
                    placeholder: "Additional details for \"" + truncateString(Core__Option.getOr(Caml_option.nullable_to_opt(todoRelation.self.text), "")) + "\"",
                    value: Core__Option.getOr(match[0], ""),
                    onChange: (function (e) {
                        setAdditionalText(function (param) {
                              return e.target.value;
                            });
                      })
                  }),
              className: "w-full flex-1 overflow-y-scroll h-full"
            });
}

var make = AdditionText;

export {
  truncateString ,
  make ,
}
/* react Not a pure module */
