// Generated by ReScript, PLEASE EDIT WITH CARE

import * as UseLocalStorageJs from "./useLocalStorage.js";
import UseLocalStorageJs$1 from "./useLocalStorage.js";

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs$1(prim0, prim1);
}

function useLocalStorageListener(prim0, prim1) {
  return UseLocalStorageJs.useLocalStorageListener(prim0, prim1);
}

export {
  useLocalStorage ,
  useLocalStorageListener ,
}
/* ./useLocalStorage.js Not a pure module */
