// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OtherJs from "./other.js";
import * as UseLocalStorageJs from "./useLocalStorage.js";
import UseLocalStorageJs$1 from "./useLocalStorage.js";

function useLocalStorage(prim0, prim1) {
  return UseLocalStorageJs$1(prim0, prim1);
}

function useLocalStorageListener(prim0, prim1) {
  return UseLocalStorageJs.useLocalStorageListener(prim0, prim1);
}

function focusPreviousClass(prim) {
  OtherJs.focusPreviousClass(prim);
}

function focusNextClass(prim) {
  OtherJs.focusNextClass(prim);
}

export {
  useLocalStorage ,
  useLocalStorageListener ,
  focusPreviousClass ,
  focusNextClass ,
}
/* ./other.js Not a pure module */
