// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./Todo.res.mjs";
import * as Theme from "./Theme.res.mjs";
import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Settings from "./Settings.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as StorageKeys from "./StorageKeys.res.mjs";
import * as AdditionText from "./AdditionText.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as Tb from "react-icons/tb";
import * as State from "@legendapp/state";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@legendapp/state/react";

function elementPosition(element) {
  var a = element.getBoundingClientRect();
  return {
          top: a.top,
          right: a.right,
          bottom: a.bottom,
          left: a.left
        };
}

var dragItem = {
  contents: undefined
};

var dropItem = {
  contents: undefined
};

function Dashboard(props) {
  var logout = props.logout;
  var root = props.root;
  var todos = props.todos;
  var match = Theme.useTheme();
  var setTheme = match[1];
  var theme = match[0];
  var match$1 = Common.useSessionStorage(StorageKeys.selectedElement, undefined);
  var setSelectedElement = match$1[1];
  var selectedElement = match$1[0];
  var match$2 = Common.useSessionStorage(StorageKeys.displayElement, undefined);
  var setDisplayElement = match$2[1];
  var displayElement = match$2[0];
  var match$3 = Common.useSessionStorage(StorageKeys.view, undefined);
  var setView = match$3[1];
  var view = match$3[0];
  var match$4 = Common.useSessionStorage(StorageKeys.showCheckboxes, false);
  var showCheckboxes = match$4[0];
  var match$5 = React.useState(function () {
        
      });
  var setChecked = match$5[1];
  var checked = match$5[0];
  var match$6 = React.useState(function () {
        return false;
      });
  var setMoveActive = match$6[1];
  var moveActive = match$6[0];
  var match$7 = React.useState(function () {
        
      });
  var setFocusClassNext = match$7[1];
  var focusClassNext = match$7[0];
  var match$8 = React.useState(function () {
        
      });
  var setFocusIdNext = match$8[1];
  var focusIdNext = match$8[0];
  var aaParentRef = React.useRef(null);
  var onMouseMove = function ($$event) {
    var match = dragItem.contents;
    if (match === undefined) {
      return ;
    }
    var mouseTop = $$event.clientY;
    var closest = {
      contents: undefined
    };
    Array.prototype.slice.call(document.getElementsByClassName("drag-marker")).forEach(function (v) {
          var best = closest.contents;
          if (best !== undefined) {
            var bestPos = elementPosition(Caml_option.valFromOption(best));
            var bestDist = Math.abs(bestPos.top - mouseTop);
            var pos = elementPosition(v);
            var dist = Math.abs(pos.top - mouseTop);
            if (dist < bestDist) {
              closest.contents = Caml_option.some(v);
            }
            
          } else {
            closest.contents = Caml_option.some(v);
          }
          v.classList.add("opacity-0");
        });
    var best = closest.contents;
    if (best === undefined) {
      return ;
    }
    var best$1 = Caml_option.valFromOption(best);
    dropItem.contents = Caml_option.some(best$1);
    best$1.classList.remove("opacity-0");
  };
  var onMouseUp = function (param) {
    Core__Option.mapOr(dragItem.contents, undefined, (function (d) {
            dragItem.contents = undefined;
            Array.prototype.slice.call(document.getElementsByClassName("drag-marker")).forEach(function (v) {
                  v.classList.add("opacity-0");
                });
            Array.prototype.slice.call(document.getElementsByClassName("drag-mask")).forEach(function (v) {
                  v.classList.remove("opacity-20");
                  v.classList.add("opacity-0");
                });
            var dropItemElement = dropItem.contents;
            if (dropItemElement === undefined) {
              return ;
            }
            var dropItemElement$1 = Caml_option.valFromOption(dropItemElement);
            Core__Option.mapOr(Types.getIdFromId(dropItemElement$1.id), undefined, (function (dropItemId) {
                    Core__Option.mapOr(todos.find(function (todo) {
                              return todo.self.id === dropItemId;
                            }), undefined, (function (dropItem) {
                            if (dropItem.self.id !== d.self.id && !dropItem.parents.includes(d.self.id)) {
                              return Core__Option.mapOr(Caml_option.nullable_to_opt(dropItem.parent), undefined, (function (parent) {
                                            State.batch(function () {
                                                  Common.setTodoParent(d.self.id, parent.id);
                                                  Core__Option.mapOr(Caml_option.nullable_to_opt(d.parent), undefined, (function (formerDragParent) {
                                                          Common.setTodoOrder(formerDragParent.id, (function (order) {
                                                                  return order.filter(function (v) {
                                                                              return v !== d.self.id;
                                                                            });
                                                                }));
                                                        }));
                                                  var bottomMarker = dropItemElement$1.classList.contains("drag-marker-bottom");
                                                  Common.setTodoOrder(parent.id, (function (order) {
                                                          return Core__Array.reduce(order, [], (function (a, c) {
                                                                        return a.concat(c === dropItem.self.id ? (
                                                                                      bottomMarker ? [
                                                                                          c,
                                                                                          d.self.id
                                                                                        ] : [
                                                                                          d.self.id,
                                                                                          c
                                                                                        ]
                                                                                    ) : [c]);
                                                                      }));
                                                        }));
                                                  Common.setTodoMode(d.self.id, dropItem.self.mode);
                                                });
                                          }));
                            }
                            
                          }));
                  }));
          }));
  };
  React.useEffect((function () {
          window.addEventListener("mousemove", onMouseMove);
          window.addEventListener("mouseup", onMouseUp);
          window.addEventListener("keydown", (function ($$event) {
                  if ($$event.key === "Alt") {
                    return setMoveActive(function (param) {
                                return true;
                              });
                  }
                  
                }));
          window.addEventListener("keyup", (function ($$event) {
                  if ($$event.key === "Alt") {
                    return setMoveActive(function (param) {
                                return false;
                              });
                  }
                  
                }));
        }), []);
  React.useEffect(function () {
        Core__Option.mapOr(Core__Option.flatMap(focusClassNext, (function (x) {
                    return Array.prototype.slice.call(document.getElementsByClassName(x))[0];
                  })), undefined, (function (element) {
                element.focus();
                setFocusClassNext(function (param) {
                      
                    });
              }));
        Core__Option.mapOr(Core__Option.flatMap(focusIdNext, (function (x) {
                    return Caml_option.nullable_to_opt(document.getElementById(x));
                  })), undefined, (function (element) {
                element.focus();
                setFocusIdNext(function (param) {
                      
                    });
              }));
      });
  if (view === "Settings") {
    return JsxRuntime.jsx(Settings.make, {
                logout: (function () {
                    setView(function (param) {
                          
                        });
                    logout();
                  }),
                backToTodos: (function () {
                    setView(function (param) {
                          
                        });
                  })
              });
  }
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx("img", {
                                          className: "py-0.5 ",
                                          src: Common.logoUrl,
                                          width: "24"
                                        }),
                                    onClick: (function (param) {
                                        setView(function (param) {
                                              return "Settings";
                                            });
                                      })
                                  }),
                              JsxRuntime.jsx("div", {
                                    className: "border-l border-[var(--t3)] mx-1 h-full bg-green-400"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: theme === "dark" ? JsxRuntime.jsx(Tb.TbSun, {
                                            className: "w-4 h-4"
                                          }) : JsxRuntime.jsx(Tb.TbMoon, {
                                            className: "w-4 h-4"
                                          }),
                                    className: "text-[var(--t6)] ",
                                    onClick: (function (param) {
                                        setTheme(function (param) {
                                              if (theme === "dark") {
                                                return "light";
                                              } else {
                                                return "dark";
                                              }
                                            });
                                      })
                                  }),
                              JsxRuntime.jsx("div", {
                                    className: "flex-1"
                                  }),
                              JsxRuntime.jsx("button", {
                                    children: JsxRuntime.jsx(Tb.TbPlus, {}),
                                    className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                                    onClick: (function (param) {
                                        var newId = Common.addTodo("", root.self.id, (function (order, id) {
                                                return [id].concat(order);
                                              }));
                                        setFocusIdNext(function (param) {
                                              return Types.getTodoInputId(newId);
                                            });
                                      })
                                  }),
                              JsxRuntime.jsx(Todo.TopCollapseControls.make, {
                                    todo: root.self,
                                    todoRelation: root,
                                    todos: todos
                                  })
                            ],
                            className: "flex-none flex flex-row gap-2 justify-between items-center w-full h-10 border-b border-[var(--t3)] px-2"
                          }),
                      JsxRuntime.jsx("ul", {
                            children: todos.map(function (todoRelation) {
                                  return JsxRuntime.jsx(Todo.make, {
                                              todoRelation: todoRelation,
                                              getTodos: (function () {
                                                  return todos;
                                                }),
                                              isSelected: Caml_obj.equal(selectedElement, todoRelation.self.id),
                                              setSelectedElement: setSelectedElement,
                                              isDisplayElement: Caml_obj.equal(displayElement, todoRelation.self.id),
                                              setDisplayElement: setDisplayElement,
                                              showCheckboxes: showCheckboxes,
                                              setFocusIdNext: setFocusIdNext,
                                              isChecked: Belt_SetString.has(checked, todoRelation.self.id),
                                              setChecked: setChecked,
                                              moveActive: moveActive,
                                              setDrag: (function () {
                                                  dragItem.contents = todoRelation;
                                                  Core__Option.mapOr(Caml_option.nullable_to_opt(document.getElementById(Types.getDragId(todoRelation.self.id))), undefined, (function (element) {
                                                          element.classList.remove("opacity-0");
                                                          element.classList.add("opacity-20");
                                                        }));
                                                })
                                            }, todoRelation.self.id);
                                }),
                            ref: Caml_option.some(aaParentRef),
                            className: "pb-5 flex-1 overflow-y-scroll"
                          }),
                      JsxRuntime.jsx("div", {
                            children: displayElement !== undefined ? Core__Option.mapOr(todos.find(function (t) {
                                        return t.self.id === displayElement;
                                      }), null, (function (todoRelation) {
                                      return JsxRuntime.jsx(AdditionText.make, {
                                                  todoRelation: todoRelation
                                                });
                                    })) : null,
                            className: "flex-none flex flex-row gap-2 justify-between items-center w-full h-20 border-t border-[var(--t3)]"
                          })
                    ],
                    className: "flex-1 flex flex-col overflow-hidden sm:h-full border-t sm:border-t-0 md:border-r max-w-4xl border-[var(--t3)]"
                  }),
              className: "flex flex-col justify-center text-[var(--t10)] h-dvh"
            });
}

var make = React$1.observer(Dashboard);

var $$default = make;

export {
  elementPosition ,
  dragItem ,
  dropItem ,
  make ,
  $$default as default,
}
/* make Not a pure module */
