// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Todo from "./Todo.res.mjs";
import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as StorageKeys from "./StorageKeys.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as State from "@legendapp/state";
import * as JsxRuntime from "react/jsx-runtime";
import * as React$1 from "@legendapp/state/react";

function elementPosition(element) {
  var a = element.getBoundingClientRect();
  return {
          top: a.top,
          right: a.right,
          bottom: a.bottom,
          left: a.left
        };
}

function Dashboard(props) {
  var root = props.root;
  var todos = props.todos;
  var match = Common.useSessionStorage(StorageKeys.selectedElement, undefined);
  var setSelectedElement = match[1];
  var selectedElement = match[0];
  var match$1 = Common.useSessionStorage(StorageKeys.displayElement, undefined);
  var setDisplayElement = match$1[1];
  var displayElement = match$1[0];
  var match$2 = Common.useSessionStorage(StorageKeys.showCheckboxes, false);
  var setShowCheckboxes = match$2[1];
  var showCheckboxes = match$2[0];
  var match$3 = React.useState(function () {
        
      });
  var setChecked = match$3[1];
  var checked = match$3[0];
  var match$4 = React.useState(function () {
        
      });
  var setFocusClassNext = match$4[1];
  var focusClassNext = match$4[0];
  var match$5 = React.useState(function () {
        
      });
  var setFocusIdNext = match$5[1];
  var focusIdNext = match$5[0];
  var aaParentRef = React.useRef(null);
  var match$6 = Common.useLocalStorage(StorageKeys.baseColor, "var(--blueBase)");
  var baseColor = match$6[0];
  var dragItem = React.useRef(undefined);
  var dropItem = React.useRef(undefined);
  var onMouseMove = function ($$event) {
    var match = dragItem.current;
    if (match === undefined) {
      return ;
    }
    var mouseTop = $$event.clientY;
    var closest = {
      contents: undefined
    };
    Array.prototype.slice.call(document.getElementsByClassName("drag-marker")).forEach(function (v) {
          var best = closest.contents;
          if (best !== undefined) {
            var bestPos = elementPosition(Caml_option.valFromOption(best));
            var bestDist = Math.abs(bestPos.top - mouseTop);
            var pos = elementPosition(v);
            var dist = Math.abs(pos.top - mouseTop);
            if (dist < bestDist) {
              closest.contents = Caml_option.some(v);
            }
            
          } else {
            closest.contents = Caml_option.some(v);
          }
          v.classList.add("opacity-0");
        });
    var best = closest.contents;
    if (best === undefined) {
      return ;
    }
    var best$1 = Caml_option.valFromOption(best);
    dropItem.current = Caml_option.some(best$1);
    best$1.classList.remove("opacity-0");
  };
  var moveItem = function () {
    var match = dragItem.current;
    var match$1 = dropItem.current;
    if (match !== undefined && match$1 !== undefined) {
      return Core__Option.mapOr(Types.getIdFromId(Caml_option.valFromOption(match$1).id), undefined, (function (dropItemId) {
                    Core__Option.mapOr(todos.find(function (todo) {
                              return todo.self.id === dropItemId;
                            }), undefined, (function (dropItem) {
                            if (dropItem.self.id !== match.self.id && !dropItem.parents.includes(match.self.id)) {
                              return Core__Option.mapOr(Caml_option.nullable_to_opt(dropItem.parent), undefined, (function (parent) {
                                            console.log("move3", dropItem.self.text, match.self.text);
                                            State.batch(function () {
                                                  Common.setTodoParent(match.self.id, parent.id);
                                                  Core__Option.mapOr(Caml_option.nullable_to_opt(match.parent), undefined, (function (formerDragParent) {
                                                          Common.setTodoOrder(formerDragParent.id, (function (order) {
                                                                  return order.filter(function (v) {
                                                                              return v !== match.self.id;
                                                                            });
                                                                }));
                                                        }));
                                                  Common.setTodoOrder(parent.id, (function (order) {
                                                          return Core__Array.reduce(order, [], (function (a, c) {
                                                                        return a.concat(c === dropItem.self.id ? [
                                                                                      c,
                                                                                      match.self.id
                                                                                    ] : [c]);
                                                                      }));
                                                        }));
                                                });
                                          }));
                            }
                            
                          }));
                  }));
    }
    
  };
  var onMouseUp = function (param) {
    Array.prototype.slice.call(document.getElementsByClassName("drag-marker")).forEach(function (v) {
          v.classList.add("opacity-0");
        });
    Array.prototype.slice.call(document.getElementsByClassName("drag-mask")).forEach(function (v) {
          v.classList.remove("opacity-20");
          v.classList.add("opacity-0");
        });
    moveItem();
    dragItem.current = undefined;
  };
  React.useEffect((function () {
          window.addEventListener("mousemove", onMouseMove);
          window.addEventListener("mouseup", onMouseUp);
        }), []);
  React.useEffect((function () {
          document.documentElement.style.setProperty("--tBase", baseColor);
        }), [baseColor]);
  React.useEffect(function () {
        Core__Option.mapOr(Core__Option.flatMap(focusClassNext, (function (x) {
                    return Array.prototype.slice.call(document.getElementsByClassName(x))[0];
                  })), undefined, (function (element) {
                element.focus();
                setFocusClassNext(function (param) {
                      
                    });
              }));
        Core__Option.mapOr(Core__Option.flatMap(focusIdNext, (function (x) {
                    return Caml_option.nullable_to_opt(document.getElementById(x));
                  })), undefined, (function (element) {
                element.focus();
                setFocusIdNext(function (param) {
                      
                    });
              }));
      });
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("button", {
                                    children: "Show Checkboxes",
                                    className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                                    onClick: (function (param) {
                                        setShowCheckboxes(function (v) {
                                              return !v;
                                            });
                                        if (showCheckboxes) {
                                          return setChecked(function (param) {
                                                      
                                                    });
                                        }
                                        
                                      })
                                  }),
                              JsxRuntime.jsx("div", {
                                    children: JsxRuntime.jsx("button", {
                                          children: "New Project",
                                          className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                                          onClick: (function (param) {
                                              var newId = Common.addTodo("", root.self.id, (function (order, id) {
                                                      return [id].concat(order);
                                                    }));
                                              setFocusIdNext(function (param) {
                                                    return Types.getTodoInputId(newId);
                                                  });
                                            })
                                        }),
                                    className: "flex flex-row items-center justify-center gap-2"
                                  })
                            ],
                            className: "flex-none flex flex-row gap-2 justify-between items-center w-full h-10 border-b border-[var(--t3)] px-2"
                          }),
                      JsxRuntime.jsxs("div", {
                            children: [
                              JsxRuntime.jsx("div", {
                                    className: "flex-1"
                                  }),
                              JsxRuntime.jsx(Todo.TopCollapseControls.make, {
                                    todo: root.self,
                                    todoRelation: root,
                                    todos: todos
                                  })
                            ],
                            className: "flex-none flex flex-row gap-2 justify-between items-center w-full h-10 border-b border-[var(--t3)] px-2"
                          }),
                      JsxRuntime.jsx("ul", {
                            children: todos.map(function (todoRelation) {
                                  return JsxRuntime.jsx(Todo.make, {
                                              todoRelation: todoRelation,
                                              getTodos: (function () {
                                                  return todos;
                                                }),
                                              isSelected: Caml_obj.equal(selectedElement, todoRelation.self.id),
                                              setSelectedElement: setSelectedElement,
                                              isDisplayElement: Caml_obj.equal(displayElement, todoRelation.self.id),
                                              setDisplayElement: setDisplayElement,
                                              showCheckboxes: showCheckboxes,
                                              setFocusIdNext: setFocusIdNext,
                                              isChecked: Belt_SetString.has(checked, todoRelation.self.id),
                                              setChecked: setChecked,
                                              setDrag: (function () {
                                                  console.log("set drag", todoRelation.self.text);
                                                  dragItem.current = todoRelation;
                                                  Core__Option.mapOr(Caml_option.nullable_to_opt(document.getElementById(Types.getDragId(todoRelation.self.id))), undefined, (function (element) {
                                                          element.classList.remove("opacity-0");
                                                          element.classList.add("opacity-20");
                                                        }));
                                                })
                                            }, todoRelation.self.id);
                                }),
                            ref: Caml_option.some(aaParentRef),
                            className: "pb-5 flex-1 overflow-y-scroll"
                          })
                    ],
                    className: "flex-1 flex flex-col overflow-hidden sm:h-full border-t sm:border-t-0 md:border-r max-w-4xl "
                  }),
              className: "flex flex-col justify-center text-[var(--t10)] h-dvh"
            });
}

var make = React$1.observer(Dashboard);

var $$default = make;

export {
  elementPosition ,
  make ,
  $$default as default,
}
/* make Not a pure module */
