// Generated by ReScript, PLEASE EDIT WITH CARE

import IsAfter from "date-fns/isAfter";
import IsEqual from "date-fns/isEqual";
import IsBefore from "date-fns/isBefore";

function isAfterOrEqual(x, y) {
  if (IsAfter(x, y)) {
    return true;
  } else {
    return IsEqual(x, y);
  }
}

function isBeforeOrEqual(x, y) {
  if (IsBefore(x, y)) {
    return true;
  } else {
    return IsEqual(x, y);
  }
}

export {
  isAfterOrEqual ,
  isBeforeOrEqual ,
}
/* date-fns/isAfter Not a pure module */
