// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as ModeMgr from "./ModeMgr.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";
import FormatISO from "date-fns/formatISO";
import ReactTextareaAutosize from "react-textarea-autosize";

function DisplayTodo(props) {
  var setFocusIdNext = props.setFocusIdNext;
  var todoRelation = props.todoRelation;
  var todo = todoRelation.self;
  var textRef = React.useRef(null);
  var additionalTextRef = React.useRef(null);
  var match = Common.useDebounce(Caml_option.nullable_to_opt(todo.text), (function (v) {
          Core__Option.mapOr(v, undefined, (function (v_) {
                  Common.setTodoText(todo.id, v_);
                }));
        }), 1000);
  var setText = match[1];
  var match$1 = Common.useDebounce(Caml_option.nullable_to_opt(todo.additional_text), (function (v) {
          Core__Option.mapOr(v, undefined, (function (v_) {
                  Common.setTodoAdditionalText(todo.id, v_);
                }));
        }), 1000);
  var setAdditionalText = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setStatusSelectIsOpen = match$2[1];
  React.useEffect((function () {
          if (Caml_obj.notequal(Caml_option.nullable_to_opt(additionalTextRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
            setAdditionalText(function (param) {
                  return Caml_option.nullable_to_opt(todo.additional_text);
                });
          }
          
        }), [todo.additional_text]);
  React.useEffect((function () {
          if (Caml_obj.notequal(Caml_option.nullable_to_opt(textRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
            setText(function (param) {
                  return Caml_option.nullable_to_opt(todo.text);
                });
          }
          
        }), [todo.text]);
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(ReactTextareaAutosize, {
                            ref: Caml_option.some(textRef),
                            className: [
                                todoRelation.depth === 0 ? "font-black" : "font-medium",
                                "text-lg flex-1 bg-inherit text-[var(--t10)] w-full outline-none \n          focus:ring-0\n           border-none p-0 "
                              ].join(" "),
                            id: "id-display-title",
                            style: {
                              resize: "none"
                            },
                            placeholder: "Todo",
                            value: Core__Option.getOr(match[0], ""),
                            onKeyDown: (function (e) {
                                if (e.key === "Escape") {
                                  return setFocusIdNext(function (param) {
                                              return Types.getTodoId(todo.id);
                                            });
                                }
                                
                              }),
                            onChange: (function (e) {
                                setText(e.target.value);
                              })
                          }),
                      className: " w-full px-2 py-1"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx(Common.StatusSelect.make, {
                              status: todo.status,
                              setStatus: (function (newStatus) {
                                  Common.setTodoStatus(todo.id, newStatus);
                                }),
                              focusTodo: (function () {
                                  
                                }),
                              isOpen: match$2[0],
                              onOpenChange: (function (v) {
                                  setStatusSelectIsOpen(function (param) {
                                        return v;
                                      });
                                }),
                              hasHidden: todoRelation.hasHiddenChildren,
                              mode: todo.mode,
                              setMode: (function (m) {
                                  Common.setTodoMode(todo.id, m);
                                })
                            }),
                        JsxRuntime.jsx(Common.DateSelect.make, {
                              value: Core__Option.map(Caml_option.nullable_to_opt(todo.target_date), (function (prim) {
                                      return new Date(prim);
                                    })),
                              onClick: (function (newDate) {
                                  Common.setTodoDate(todo.id, Common.toNullableNull(Core__Option.map(newDate, (function (x) {
                                                  return FormatISO(x, {
                                                              format: undefined,
                                                              representation: "date"
                                                            });
                                                }))));
                                }),
                              className: "mr-1 ml-1"
                            }),
                        JsxRuntime.jsx("div", {
                              className: "flex-1"
                            }),
                        JsxRuntime.jsx("button", {
                              children: JsxRuntime.jsx(Tb.TbTrash, {}),
                              className: ["\n          text-[var(--t4)] px-1 h-6 flex flex-row items-center justify-center rounded border-[var(--t3)]\n          hover:text-blue-600\n        "].join(" "),
                              onClick: (function (param) {
                                  Core__Option.mapOr(Caml_option.nullable_to_opt(document.getElementById(Types.getTodoId(todo.id))), undefined, (function (todoEl) {
                                          Common.focusPreviousClass(Types.listItemClass, todoEl);
                                        }));
                                  Common.deleteTodoAndMoveChildren(todoRelation);
                                })
                            })
                      ],
                      className: "flex flex-row flex-wrap border-y border-[var(--t3)] items-center gap-1 p-1 px-2"
                    }),
                todoRelation.children.length > 0 ? JsxRuntime.jsx(ModeMgr.make, {
                        todo: todo
                      }) : null,
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx(ReactTextareaAutosize, {
                            ref: Caml_option.some(additionalTextRef),
                            className: ["placeholder:text-[var(--t5)] text-sm flex-1 border-none rounded-lg text-[var(--t10)] w-full outline-none bg-[var(--t2)]\n          focus:ring-0 font-medium"].join(" "),
                            id: "id-display-title",
                            style: {
                              resize: "none"
                            },
                            placeholder: "Additional Details",
                            value: Core__Option.getOr(match$1[0], ""),
                            onChange: (function (e) {
                                setAdditionalText(function (param) {
                                      return e.target.value;
                                    });
                              })
                          }),
                      className: "p-2 pt-0"
                    })
              ],
              className: "w-full flex-1 overflow-y-scroll"
            });
}

var make = DisplayTodo;

export {
  make ,
}
/* react Not a pure module */
