// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.res.mjs";
import * as Dashboard from "./Dashboard.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as JsxRuntime from "react/jsx-runtime";

function Entry(props) {
  var todos = Core__Array.reduce(props.input, undefined, (function (a, c) {
          var key = Core__Option.getOr(Caml_option.nullable_to_opt(c.parent_todo), "root");
          return Belt_MapString.update(a, key, (function (o) {
                        if (o !== undefined) {
                          return o.concat([c]);
                        } else {
                          return [c];
                        }
                      }));
        }));
  var filterer = function (arr, c) {
    return arr.filter(function (x) {
                return c.modes_shown.includes(x.mode);
              });
  };
  var checkIfHiddenChildren = function (arr, c) {
    return !arr.every(function (x) {
                return c.modes_shown.includes(x.mode);
              });
  };
  var checkIfArchivedChildren = function (arr, c) {
    return arr.some(function (v) {
                return v.mode === "Archive";
              });
  };
  var checkIfStashedChildren = function (arr, c) {
    return arr.some(function (v) {
                return v.mode === "Stashed";
              });
  };
  var recurse = function (sibs, depth, parent, tios, parentIndex, showAll) {
    return Core__Array.reduceWithIndex(sibs, [], (function (a, self, index) {
                  var match = Core__Option.mapOr(Belt_MapString.get(todos, self.id), [
                        [],
                        []
                      ], (function (children) {
                          var hasStashed = {
                            contents: false
                          };
                          var hasArchived = {
                            contents: false
                          };
                          var children$1 = children.toSorted(function (a, b) {
                                  var result = 0;
                                  if (result === 0) {
                                    result = Types.modeCompare(a.mode) - Types.modeCompare(b.mode);
                                  }
                                  if (result === 0) {
                                    var len = self.order.length;
                                    var aIndex = self.order.indexOf(a.id);
                                    var bIndex = self.order.indexOf(b.id);
                                    var aIndex$1 = aIndex === -1 ? len : aIndex;
                                    var bIndex$1 = bIndex === -1 ? len : bIndex;
                                    result = aIndex$1 - bIndex$1 | 0;
                                  }
                                  if (result === 0) {
                                    result = Core__Option.getOr(Caml_option.nullable_to_opt(a.text), "").localeCompare(Core__Option.getOr(Caml_option.nullable_to_opt(b.text), ""));
                                  }
                                  return result;
                                }).map(function (child) {
                                if (!hasStashed.contents && child.mode === "Stashed") {
                                  hasStashed.contents = true;
                                  return {
                                          id: child.id,
                                          counter: child.counter,
                                          text: child.text,
                                          additional_text: child.additional_text,
                                          created_at: child.created_at,
                                          updated_at: child.updated_at,
                                          parent_todo: child.parent_todo,
                                          deleted: child.deleted,
                                          user_id: child.user_id,
                                          order: child.order,
                                          status: child.status,
                                          target_date: child.target_date,
                                          mode: child.mode,
                                          modes_shown: child.modes_shown,
                                          is_first_of_mode: "Stashed"
                                        };
                                } else if (!hasArchived.contents && child.mode === "Archive") {
                                  hasArchived.contents = true;
                                  return {
                                          id: child.id,
                                          counter: child.counter,
                                          text: child.text,
                                          additional_text: child.additional_text,
                                          created_at: child.created_at,
                                          updated_at: child.updated_at,
                                          parent_todo: child.parent_todo,
                                          deleted: child.deleted,
                                          user_id: child.user_id,
                                          order: child.order,
                                          status: child.status,
                                          target_date: child.target_date,
                                          mode: child.mode,
                                          modes_shown: child.modes_shown,
                                          is_first_of_mode: "Archive"
                                        };
                                } else {
                                  return child;
                                }
                              });
                          return [
                                  children$1,
                                  recurse(showAll ? children$1 : filterer(children$1, self), depth + 1 | 0, self, sibs, index, showAll)
                                ];
                        }));
                  var children = match[0];
                  var newItem_hasHiddenChildren = showAll ? false : checkIfHiddenChildren(children, self);
                  var newItem_hasArchivedChildren = checkIfArchivedChildren(children, self);
                  var newItem_hasStashedChildren = checkIfStashedChildren(children, self);
                  var newItem = {
                    self: self,
                    depth: depth,
                    index: index,
                    parent: parent,
                    hasHiddenChildren: newItem_hasHiddenChildren,
                    hasArchivedChildren: newItem_hasArchivedChildren,
                    hasStashedChildren: newItem_hasStashedChildren,
                    parentIndex: parentIndex,
                    tios: tios,
                    sibs: sibs,
                    children: children
                  };
                  return a.concat([newItem]).concat(match[1]);
                }));
  };
  var todosToDisplay = Core__Option.mapOr(Belt_MapString.get(todos, "root"), [], (function (root) {
            return recurse(root.filter(function (x) {
                            return x.mode === "Working";
                          }), 0, null, [], 0, false);
          })).filter(function (x) {
        return x.depth !== 0;
      });
  var allTodos = Core__Option.mapOr(Belt_MapString.get(todos, "root"), [], (function (root) {
          return recurse(root, 0, null, [], 0, true);
        }));
  return JsxRuntime.jsx(Dashboard.make, {
              todos: todosToDisplay,
              allTodos: allTodos,
              logout: props.logout
            });
}

var make = Entry;

var $$default = Entry;

export {
  make ,
  $$default as default,
}
/* Types Not a pure module */
