// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Dashboard from "./Dashboard.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as JsxRuntime from "react/jsx-runtime";

function Entry(props) {
  var todos = Common.groupByAndSort(props.input, (function (x) {
          return Caml_option.nullable_to_opt(x.parent_todo);
        }), (function (x) {
          return x.position;
        }));
  var filterer = function (arr, c) {
    return arr.filter(function (x) {
                return c.modes_shown.includes(x.mode);
              });
  };
  var checkIfHiddenChildren = function (arr, c) {
    return !arr.every(function (x) {
                return c.modes_shown.includes(x.mode);
              });
  };
  var recurse = function (sibs, depth, parent, tios, parentIndex, showAll) {
    return Core__Array.reduceWithIndex(sibs, [], (function (a, self, index) {
                  var match = Core__Option.mapOr(Belt_MapString.get(todos, self.id), [
                        [],
                        []
                      ], (function (children) {
                          return [
                                  children,
                                  recurse(showAll ? children : filterer(children, self), depth + 1 | 0, self, sibs, index, showAll)
                                ];
                        }));
                  var children = match[0];
                  var newItem_hasHiddenChildren = showAll ? false : checkIfHiddenChildren(children, self);
                  var newItem = {
                    self: self,
                    depth: depth,
                    index: index,
                    parent: parent,
                    hasHiddenChildren: newItem_hasHiddenChildren,
                    parentIndex: parentIndex,
                    tios: tios,
                    sibs: sibs,
                    children: children
                  };
                  return a.concat([newItem]).concat(match[1]);
                }));
  };
  var todosToDisplay = Core__Option.mapOr(Belt_MapString.get(todos, "root"), [], (function (root) {
          return recurse(root.filter(function (x) {
                          return x.mode === "Working";
                        }), 0, null, [], 0, false);
        }));
  var allTodos = Core__Option.mapOr(Belt_MapString.get(todos, "root"), [], (function (root) {
          return recurse(root, 0, null, [], 0, true);
        }));
  return JsxRuntime.jsx(Dashboard.make, {
              todos: todosToDisplay,
              allTodos: allTodos,
              logout: props.logout,
              rootTodos: Core__Option.getOr(Belt_MapString.get(todos, "root"), [])
            });
}

var make = Entry;

var $$default = Entry;

export {
  make ,
  $$default as default,
}
/* Common Not a pure module */
