// Generated by ReScript, PLEASE EDIT WITH CARE


var EyeClosed = {};

var Eye = {};

var Slash = {};

var CircleSlash = {};

var X = {};

var Check = {};

var Plus = {};

var Minus = {};

var Trash = {};

var Pin = {};

var Archive = {};

var ArchiveOff = {};

var CornerDownRight = {};

var DragDrop = {};

var SquarePlus = {};

var ChevronDown = {};

var ChevronUp = {};

var ArrowLeft = {};

var ArrowRight = {};

export {
  EyeClosed ,
  Eye ,
  Slash ,
  CircleSlash ,
  X ,
  Check ,
  Plus ,
  Minus ,
  Trash ,
  Pin ,
  Archive ,
  ArchiveOff ,
  CornerDownRight ,
  DragDrop ,
  SquarePlus ,
  ChevronDown ,
  ChevronUp ,
  ArrowLeft ,
  ArrowRight ,
}
/* No side effect */
