// Generated by ReScript, PLEASE EDIT WITH CARE


var EyeClosed = {};

var Eye = {};

var Slash = {};

var CircleSlash = {};

var X = {};

var Check = {};

var Plus = {};

var Minus = {};

var Trash = {};

var Pin = {};

var Archive = {};

var ArchiveOff = {};

var CornerDownRight = {};

var DragDrop = {};

var SquarePlus = {};

var ChevronDown = {};

var ChevronUp = {};

var ChevronRight = {};

var ChevronLeft = {};

var ArrowLeft = {};

var ArrowRight = {};

var Play = {};

var Pause = {};

var Stop = {};

var Stash = {};

var Inbox = {};

var Bookmark = {};

var Exclamation = {};

var Question = {};

var Future = {};

var Clock = {};

export {
  EyeClosed ,
  Eye ,
  Slash ,
  CircleSlash ,
  X ,
  Check ,
  Plus ,
  Minus ,
  Trash ,
  Pin ,
  Archive ,
  ArchiveOff ,
  CornerDownRight ,
  DragDrop ,
  SquarePlus ,
  ChevronDown ,
  ChevronUp ,
  ChevronRight ,
  ChevronLeft ,
  ArrowLeft ,
  ArrowRight ,
  Play ,
  Pause ,
  Stop ,
  Stash ,
  Inbox ,
  Bookmark ,
  Exclamation ,
  Question ,
  Future ,
  Clock ,
}
/* No side effect */
