// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as State from "@legendapp/state";
import * as JsxRuntime from "react/jsx-runtime";

function ModeMgr(props) {
  var todos = props.todos;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Stash to Working",
                              className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                              onClick: (function (param) {
                                  State.batch(function () {
                                        todos.filter(function (x) {
                                                return x.mode === "Stashed";
                                              }).forEach(function (x) {
                                              Common.setTodoMode(x.id, "Working");
                                            });
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Working to Stash ",
                              className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                              onClick: (function (param) {
                                  State.batch(function () {
                                        todos.filter(function (x) {
                                                return x.mode === "Working";
                                              }).forEach(function (x) {
                                              Common.setTodoMode(x.id, "Stashed");
                                            });
                                      });
                                })
                            })
                      ],
                      className: "flex flex-row gap-1 p-2"
                    }),
                Core__Option.mapOr(props.todo, null, (function (todo) {
                        return JsxRuntime.jsxs("div", {
                                    children: [
                                      JsxRuntime.jsx("button", {
                                            children: "W",
                                            className: [
                                                todo.show_mode === "Working" ? "bg-[var(--t3)]" : "",
                                                "px-2 py-0.5 text-xs flex flex-row items-center justify-center rounded"
                                              ].join(" "),
                                            onClick: (function (param) {
                                                Common.setTodoShowMode(todo.id, "Working");
                                              })
                                          }),
                                      JsxRuntime.jsx("button", {
                                            children: "W+S",
                                            className: [
                                                todo.show_mode === "Stashed" ? "bg-[var(--t3)]" : "",
                                                "px-2 py-0.5 text-xs flex flex-row items-center justify-center rounded"
                                              ].join(" "),
                                            onClick: (function (param) {
                                                Common.setTodoShowMode(todo.id, "Stashed");
                                              })
                                          }),
                                      JsxRuntime.jsx("button", {
                                            children: "W+S+A",
                                            className: [
                                                todo.show_mode === "Archive" ? "bg-[var(--t3)]" : "",
                                                "px-2 py-0.5 text-xs flex flex-row items-center justify-center rounded"
                                              ].join(" "),
                                            onClick: (function (param) {
                                                Common.setTodoShowMode(todo.id, "Archive");
                                              })
                                          })
                                    ],
                                    className: "flex flex-row gap-1 rounded p-1"
                                  });
                      })),
                JsxRuntime.jsx("div", {
                      children: todos.map(function (todo) {
                            return JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("button", {
                                                        children: "W",
                                                        className: [
                                                            todo.mode === "Working" ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            Common.setTodoMode(todo.id, "Working");
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: "S",
                                                        className: [
                                                            todo.mode === "Stashed" ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            Common.setTodoMode(todo.id, "Stashed");
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("button", {
                                                        children: "A",
                                                        className: [
                                                            todo.mode === "Archive" ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            Common.setTodoMode(todo.id, "Archive");
                                                          })
                                                      })
                                                ],
                                                className: "flex flex-row gap-1 rounded p-1"
                                              }),
                                          JsxRuntime.jsx("div", {
                                                children: Core__Option.getOr(Caml_option.nullable_to_opt(todo.text), ""),
                                                className: "max-w-80  flex flex-row items-center rounded"
                                              })
                                        ],
                                        className: ["text-sm px-2 min-h-6  flex flex-row items-center rounded gap-1 "].join(" ")
                                      });
                          }),
                      className: "flex flex-col p-2 cursor-pointer divide-y"
                    })
              ]
            });
}

var make = ModeMgr;

export {
  make ,
}
/* Common Not a pure module */
