// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.res.mjs";
import * as Common from "./Common.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Settings(props) {
  var logout = props.logout;
  var setBaseColor = props.setBaseColor;
  var match = Theme.useTheme();
  var setTheme = match[1];
  var theme = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "py-0.5 ",
                              src: Common.logoUrl,
                              width: "40"
                            }),
                        JsxRuntime.jsx("div", {
                              children: "Tiger Todo",
                              className: "font-black text-5xl tracking-tighter"
                            })
                      ],
                      className: "flex flex-row gap-3 ml-0.5"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: "Tiger is a todo app with one special feature: it is designed exclusively for my girlfriend.\n            You can use it too if you like it.\n            ",
                            className: " mb-4 mt-2"
                          }),
                      className: "font-normal text-sm"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: "Logout",
                            className: "text-sm px-2 bg-[var(--t2)] rounded",
                            onClick: (function (param) {
                                logout();
                              })
                          }),
                      className: "flex flex-row justify-end w-full"
                    }),
                JsxRuntime.jsx("div", {
                      children: "Settings",
                      className: "font-black text-xl"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Color Theme",
                              className: "font-bold pb-1"
                            }),
                        JsxRuntime.jsx("div", {
                              children: [
                                  "var(--redBase)",
                                  "var(--orangeBase)",
                                  "var(--yellowBase)",
                                  "var(--greenBase)",
                                  "var(--tealBase)",
                                  "var(--blueBase)",
                                  "var(--purpleBase)",
                                  "var(--pinkBase)"
                                ].map(function (v) {
                                    return JsxRuntime.jsx("button", {
                                                className: "h-6 w-6 rounded-full",
                                                style: {
                                                  backgroundColor: theme === "dark" ? "oklch(from " + v + " 0.4 0.2 h)" : "oklch(from " + v + " 0.8 0.2 h)"
                                                },
                                                onClick: (function (param) {
                                                    setBaseColor(function (param) {
                                                          return v;
                                                        });
                                                  })
                                              }, v);
                                  }),
                              className: "flex flex-row gap-2 py-1"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Dark Mode",
                                      className: "text-sm px-2 bg-[var(--t2)] rounded",
                                      onClick: (function (param) {
                                          setTheme(function (param) {
                                                return "dark";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Light Mode",
                                      className: "text-sm px-2 bg-[var(--t2)] rounded",
                                      onClick: (function (param) {
                                          setTheme(function (param) {
                                                return "light";
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-row gap-2 py-2"
                            })
                      ],
                      className: ""
                    }),
                JsxRuntime.jsx("div", {
                      children: "Backup",
                      className: "font-bold"
                    }),
                JsxRuntime.jsx("div", {
                      className: "flex flex-row gap-2 mb-2"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        "Made by ",
                        JsxRuntime.jsx("a", {
                              children: "Thomas Wright",
                              style: {
                                color: theme === "dark" ? "oklch(from var(--tBase) 0.7 0.2 h)" : "oklch(from var(--tBase) 0.5 0.2 h)"
                              },
                              href: "https://github.com/thomaswright/tiger"
                            })
                      ],
                      className: "text-xs text-right w-full py-3 px-2 font-bold "
                    })
              ],
              className: "flex-1 overflow-y-scroll px-3 py-2 flex flex-col gap-2 items-start pb-2"
            });
}

var make = Settings;

export {
  make ,
}
/* Theme Not a pure module */
