// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Theme from "./Theme.res.mjs";
import * as Common from "./Common.res.mjs";
import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function Settings(props) {
  var backToTodos = props.backToTodos;
  var logout = props.logout;
  var setBaseColor = props.setBaseColor;
  var match = Theme.useTheme();
  var setTheme = match[1];
  var theme = match[0];
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("button", {
                      children: JsxRuntime.jsx(Tb.TbArrowLeft, {}),
                      className: "my-2",
                      onClick: (function (param) {
                          backToTodos();
                        })
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("img", {
                              className: "py-0.5",
                              src: Common.logoUrl,
                              width: "24"
                            }),
                        JsxRuntime.jsx("div", {
                              children: "Tiger Todo",
                              className: "font-bold text-2xl"
                            })
                      ],
                      className: "flex flex-row gap-2 items-center"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("div", {
                            children: "This todo app has one special feature: it is designed exclusively for my girlfriend.\n            You can use it too if you like it.\n            ",
                            className: "pt-3 max-w-sm"
                          }),
                      className: "font-normal text-sm"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("div", {
                              children: "Theme",
                              className: "font-bold leading-none"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx("button", {
                                      children: "Dark",
                                      className: "text-sm px-3 py-0.5 bg-[var(--t2)] rounded",
                                      onClick: (function (param) {
                                          setTheme(function (param) {
                                                return "dark";
                                              });
                                        })
                                    }),
                                JsxRuntime.jsx("button", {
                                      children: "Light",
                                      className: "text-sm px-3 py-0.5 bg-[var(--t2)] rounded",
                                      onClick: (function (param) {
                                          setTheme(function (param) {
                                                return "light";
                                              });
                                        })
                                    })
                              ],
                              className: "flex flex-row gap-2 "
                            }),
                        JsxRuntime.jsx("div", {
                              children: [
                                  "var(--redBase)",
                                  "var(--orangeBase)",
                                  "var(--yellowBase)",
                                  "var(--greenBase)",
                                  "var(--tealBase)",
                                  "var(--blueBase)",
                                  "var(--purpleBase)",
                                  "var(--pinkBase)"
                                ].map(function (v) {
                                    return JsxRuntime.jsx("button", {
                                                className: "h-6 w-6 rounded-full",
                                                style: {
                                                  backgroundColor: theme === "dark" ? "oklch(from " + v + " 0.4 0.2 h)" : "oklch(from " + v + " 0.8 0.2 h)"
                                                },
                                                onClick: (function (param) {
                                                    setBaseColor(function (param) {
                                                          return v;
                                                        });
                                                  })
                                              }, v);
                                  }),
                              className: "flex flex-row gap-2"
                            })
                      ],
                      className: "flex flex-col gap-3  py-3"
                    }),
                JsxRuntime.jsx("div", {
                      children: JsxRuntime.jsx("button", {
                            children: "Logout",
                            className: "text-sm px-3 py-0.5 bg-[var(--t2)] rounded",
                            onClick: (function (param) {
                                logout();
                              })
                          }),
                      className: "flex flex-row justify-start py-2"
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        "Made by ",
                        JsxRuntime.jsx("a", {
                              children: "Thomas Wright",
                              style: {
                                color: theme === "dark" ? "oklch(from var(--tBase) 0.7 0.2 h)" : "oklch(from var(--tBase) 0.5 0.2 h)"
                              },
                              href: "https://github.com/thomaswright/tiger"
                            })
                      ],
                      className: "text-xs w-full font-bold py-3 "
                    })
              ],
              className: "flex-1 overflow-y-scroll px-3 py-2 flex flex-col items-start"
            });
}

var make = Settings;

export {
  make ,
}
/* Theme Not a pure module */
