// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Common from "./Common.res.mjs";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function StashMgr(props) {
  var todos = props.todos;
  var setStashed = props.setStashed;
  var stashed = props.stashed;
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("button", {
                              children: "Unstash All",
                              className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                              onClick: (function (param) {
                                  setStashed(function (param) {
                                        return [];
                                      });
                                })
                            }),
                        JsxRuntime.jsx("button", {
                              children: "Stash All ",
                              className: "px-2 bg-[var(--t2)] rounded text-sm h-5",
                              onClick: (function (param) {
                                  setStashed(function (param) {
                                        return todos.map(function (x) {
                                                    return x.id;
                                                  });
                                      });
                                })
                            })
                      ],
                      className: "flex flex-row gap-1 p-2"
                    }),
                JsxRuntime.jsx("div", {
                      children: todos.map(function (todo) {
                            var isStashed = stashed.includes(todo.id);
                            return JsxRuntime.jsxs("div", {
                                        children: [
                                          JsxRuntime.jsxs("div", {
                                                children: [
                                                  JsxRuntime.jsx("div", {
                                                        children: "W",
                                                        className: [
                                                            !isStashed && !todo.hidden ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            setStashed(function (v) {
                                                                  return v.filter(function (x) {
                                                                              return x !== todo.id;
                                                                            });
                                                                });
                                                            Common.setTodoHidden(todo.id, false);
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("div", {
                                                        children: "S",
                                                        className: [
                                                            isStashed && !todo.hidden ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            setStashed(function (v) {
                                                                  if (v.includes(todo.id)) {
                                                                    return v;
                                                                  } else {
                                                                    return v.concat([todo.id]);
                                                                  }
                                                                });
                                                            Common.setTodoHidden(todo.id, false);
                                                          })
                                                      }),
                                                  JsxRuntime.jsx("div", {
                                                        children: "A",
                                                        className: [
                                                            todo.hidden ? "bg-[var(--t3)]" : "",
                                                            "w-5 flex flex-row items-center justify-center rounded"
                                                          ].join(" "),
                                                        onClick: (function (param) {
                                                            setStashed(function (v) {
                                                                  return v.filter(function (x) {
                                                                              return x !== todo.id;
                                                                            });
                                                                });
                                                            Common.setTodoHidden(todo.id, true);
                                                          })
                                                      })
                                                ],
                                                className: "flex flex-row gap-1 rounded p-1"
                                              }),
                                          JsxRuntime.jsx("div", {
                                                children: Core__Option.getOr(Caml_option.nullable_to_opt(todo.text), ""),
                                                className: "max-w-80  flex flex-row items-center rounded"
                                              })
                                        ],
                                        className: ["text-sm px-2 min-h-6  flex flex-row items-center rounded gap-1 "].join(" ")
                                      });
                          }),
                      className: "flex flex-col p-2 cursor-pointer divide-y"
                    })
              ]
            });
}

var make = StashMgr;

export {
  make ,
}
/* Common Not a pure module */
