// Generated by ReScript, PLEASE EDIT WITH CARE


var theme = "tiger-theme";

var baseColor = "tiger-baseColor";

var selectedElement = "tiger-selected-element";

var displayElement = "tiger-display-element";

var view = "tiger-view";

var showCheckboxes = "tiger-show-checkboxes";

export {
  theme ,
  baseColor ,
  selectedElement ,
  displayElement ,
  view ,
  showCheckboxes ,
}
/* No side effect */
