// Generated by ReScript, PLEASE EDIT WITH CARE


var theme = "tiger-theme";

var projects = "tiger-projects";

var projectsTab = "tiger-projectsTab";

var baseColor = "tiger-baseColor";

export {
  theme ,
  projects ,
  projectsTab ,
  baseColor ,
}
/* No side effect */
