// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Common from "./Common.res.mjs";

function useTheme() {
  var match = Common.useLocalStorage("theme", "light");
  var theme = match[0];
  React.useEffect((function () {
          var match = theme === "dark" ? [
              "light",
              "dark"
            ] : [
              "dark",
              "light"
            ];
          document.documentElement.classList.remove(match[0]);
          document.documentElement.classList.add(match[1]);
        }), [theme]);
  return [
          theme,
          match[1]
        ];
}

export {
  useTheme ,
}
/* react Not a pure module */
