// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as Tb from "react-icons/tb";
import * as State from "@legendapp/state";
import * as JsxRuntime from "react/jsx-runtime";
import FormatISO from "date-fns/formatISO";
import ReactTextareaAutosize from "react-textarea-autosize";

function Todo$TopCollapseControls(props) {
  var todos = props.todos;
  var todoRelation = props.todoRelation;
  var todo = props.todo;
  var someExpanded = todos.some(function (v) {
        if (v.depth === 1) {
          return v.self.modes_shown.length > 0;
        } else {
          return false;
        }
      });
  return JsxRuntime.jsxs("div", {
              children: [
                todoRelation.hasStashedChildren ? JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx(Tb.TbBookmark, {}),
                        className: [
                            todo.modes_shown.includes("Stashed") ? "text-[var(--t7)]" : "text-[var(--t3)]",
                            " flex flex-row items-center justify-center rounded "
                          ].join(" "),
                        onClick: (function (param) {
                            Common.setTodoModesShown(todo.id, (function (a) {
                                    return Common.arrayToggle(a, "Stashed");
                                  }));
                          })
                      }) : null,
                todoRelation.hasArchivedChildren ? JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx(Tb.TbArchive, {}),
                        className: [
                            todo.modes_shown.includes("Archive") ? " text-[var(--t7)]" : "text-[var(--t3)]",
                            " flex flex-row items-center justify-center rounded"
                          ].join(" "),
                        onClick: (function (param) {
                            Common.setTodoModesShown(todo.id, (function (a) {
                                    return Common.arrayToggle(a, "Archive");
                                  }));
                          })
                      }) : null,
                someExpanded ? JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx(Tb.TbChevronDown, {}),
                        className: "mr-4  text-[var(--t5)]  text-sm",
                        onClick: (function (param) {
                            State.batch(function () {
                                  todos.forEach(function (t) {
                                        Common.setTodoModesShown(t.self.id, (function (param) {
                                                return [];
                                              }));
                                      });
                                });
                          })
                      }) : JsxRuntime.jsx("button", {
                        children: JsxRuntime.jsx(Tb.TbMinus, {}),
                        className: "mr-4 text-[var(--t5)] text-sm",
                        onClick: (function (param) {
                            State.batch(function () {
                                  todos.forEach(function (t) {
                                        Common.setTodoModesShown(t.self.id, (function (param) {
                                                return ["Working"];
                                              }));
                                      });
                                });
                          })
                      })
              ],
              className: "flex flex-row gap-2"
            });
}

var TopCollapseControls = {
  make: Todo$TopCollapseControls
};

function Todo$CollapseControls(props) {
  var todoRelation = props.todoRelation;
  if (todoRelation.children.length <= 0) {
    return null;
  }
  var todo = props.todo;
  return JsxRuntime.jsx("div", {
              children: todo.modes_shown.length === 0 ? JsxRuntime.jsx(React.Fragment, {
                      children: JsxRuntime.jsx("button", {
                            children: JsxRuntime.jsx(Tb.TbChevronDown, {}),
                            className: "mr-4 text-[var(--t5)]",
                            onClick: (function (param) {
                                Common.setTodoModesShown(todo.id, (function (a) {
                                        return Common.arrayToggle(a, "Working");
                                      }));
                              })
                          })
                    }) : JsxRuntime.jsxs(React.Fragment, {
                      children: [
                        todoRelation.hasStashedChildren ? JsxRuntime.jsx("button", {
                                children: JsxRuntime.jsx(Tb.TbBookmark, {}),
                                className: [
                                    todo.modes_shown.includes("Stashed") ? "text-[var(--t7)]" : "text-[var(--t3)]",
                                    " flex flex-row items-center justify-center rounded "
                                  ].join(" "),
                                onClick: (function (param) {
                                    Common.setTodoModesShown(todo.id, (function (a) {
                                            return Common.arrayToggle(a, "Stashed");
                                          }));
                                  })
                              }) : null,
                        todoRelation.hasArchivedChildren ? JsxRuntime.jsx("button", {
                                children: JsxRuntime.jsx(Tb.TbArchive, {}),
                                className: [
                                    todo.modes_shown.includes("Archive") ? " text-[var(--t7)]" : "text-[var(--t3)]",
                                    " flex flex-row items-center justify-center rounded"
                                  ].join(" "),
                                onClick: (function (param) {
                                    Common.setTodoModesShown(todo.id, (function (a) {
                                            return Common.arrayToggle(a, "Archive");
                                          }));
                                  })
                              }) : null,
                        JsxRuntime.jsx("button", {
                              children: JsxRuntime.jsx(Tb.TbMinus, {}),
                              className: "mr-4  text-[var(--t5)]",
                              onClick: (function (param) {
                                  Common.setTodoModesShown(todo.id, (function (param) {
                                          return [];
                                        }));
                                })
                            })
                      ]
                    }),
              className: "flex flex-row gap-2"
            });
}

var CollapseControls = {
  make: Todo$CollapseControls
};

function Todo(props) {
  var setDrag = props.setDrag;
  var setChecked = props.setChecked;
  var isChecked = props.isChecked;
  var setFocusIdNext = props.setFocusIdNext;
  var setDisplayElement = props.setDisplayElement;
  var isDisplayElement = props.isDisplayElement;
  var setSelectedElement = props.setSelectedElement;
  var isSelected = props.isSelected;
  var todoRelation = props.todoRelation;
  var todo = todoRelation.self;
  var match = React.useState(function () {
        return false;
      });
  var setStatusSelectIsOpen = match[1];
  var match$1 = Common.useDebounce(Caml_option.nullable_to_opt(todo.text), (function (v) {
          Core__Option.mapOr(v, undefined, (function (v_) {
                  Common.setTodoText(todo.id, v_);
                }));
        }), 1000);
  var setText = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setStagedForDelete = match$2[1];
  var stagedForDelete = match$2[0];
  var inputRef = React.useRef(null);
  var containerRef = React.useRef(null);
  React.useEffect((function () {
          if (Caml_obj.notequal(Caml_option.nullable_to_opt(inputRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
            setText(function (param) {
                  return Caml_option.nullable_to_opt(todo.text);
                });
          }
          
        }), [todo.text]);
  var focusContainer = function () {
    Common.mapNullable(containerRef.current, (function (dom) {
            dom.focus();
          }));
  };
  var indentation = function (e) {
    if (e.key === "Tab") {
      e.preventDefault();
    }
    if (e.key === "Tab" && !e.shiftKey || e.key === "]" && e.metaKey) {
      e.preventDefault();
      State.batch(function () {
            Core__Option.mapOr(todoRelation.sibs[todoRelation.index - 1 | 0], undefined, (function (prevSib) {
                    if (prevSib.mode !== todo.mode) {
                      return ;
                    } else {
                      Common.setTodoParent(todo.id, prevSib.id);
                      Common.setTodoModesShown(prevSib.id, (function (modes) {
                              if (modes.includes("Working")) {
                                return modes;
                              } else {
                                return Belt_Array.concatMany([
                                            modes,
                                            ["Working"]
                                          ]);
                              }
                            }));
                      Common.setTodoOrder(prevSib.id, (function (order) {
                              return order.concat([todo.id]);
                            }));
                      return Common.setTodoMode(todo.id, prevSib.modes_shown.includes("Archive") ? "Archive" : (
                                    prevSib.modes_shown.includes("Stashed") ? "Stashed" : "Working"
                                  ));
                    }
                  }));
          });
    }
    if ((e.key === "Tab" && e.shiftKey || e.key === "[" && e.metaKey) && !(todo.parent_todo == null)) {
      e.preventDefault();
      State.batch(function () {
            Core__Option.mapOr(Caml_option.nullable_to_opt(todoRelation.parent), undefined, (function (parent) {
                    Core__Option.mapOr(Caml_option.nullable_to_opt(parent.parent_todo), undefined, (function (grandParent) {
                            Common.setTodoParent(todo.id, grandParent);
                            Common.setTodoOrder(parent.id, (function (order) {
                                    return order.filter(function (v) {
                                                return v !== todo.id;
                                              });
                                  }));
                            Common.setTodoOrder(grandParent, (function (order) {
                                    return Core__Array.reduce(order, [], (function (a, c) {
                                                  return a.concat(c === parent.id ? [
                                                                c,
                                                                todo.id
                                                              ] : [c]);
                                                }));
                                  }));
                          }));
                  }));
          });
      return ;
    }
    
  };
  var makeNewTodo = function () {
    if (!(todoRelation.children.length > 0 && todoRelation.self.modes_shown.length > 0)) {
      return Core__Option.mapOr(Caml_option.nullable_to_opt(todo.parent_todo), undefined, (function (parent_todo) {
                    var newId = Common.addTodo("", parent_todo, (function (order, id) {
                            return Core__Array.reduce(order, [], (function (a, c) {
                                          return a.concat(c === todo.id ? [
                                                        c,
                                                        id
                                                      ] : [c]);
                                        }));
                          }));
                    Common.setTodoMode(newId, todo.mode);
                    setFocusIdNext(function (param) {
                          return Types.getTodoInputId(newId);
                        });
                  }));
    }
    Common.setTodoModesShown(todo.id, (function (a) {
            if (a.includes("Working")) {
              return a;
            } else {
              return a.concat(["Working"]);
            }
          }));
    var newId = Common.addTodo("", todo.id, (function (order, id) {
            return [id].concat(order);
          }));
    setFocusIdNext(function (param) {
          return Types.getTodoInputId(newId);
        });
  };
  var onKeyDownContainer = function (e) {
    if (isSelected && Caml_obj.equal(Caml_option.nullable_to_opt(containerRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
      return Common.mapNullable(containerRef.current, (function (dom) {
                    if (e.key === "s") {
                      e.preventDefault();
                      setStatusSelectIsOpen(function (param) {
                            return true;
                          });
                    }
                    if (e.key === "ArrowUp") {
                      e.preventDefault();
                      Common.focusPreviousClass(Types.listItemClass, dom);
                    }
                    if (e.key === "ArrowDown") {
                      e.preventDefault();
                      Common.focusNextClass(Types.listItemClass, dom);
                    }
                    if (e.key === "Backspace" && e.metaKey) {
                      Common.deleteTodoAndMoveChildren(todoRelation);
                      Common.mapNullable(containerRef.current, (function (containerEl) {
                              Common.focusPreviousClass(Types.listItemClass, containerEl);
                            }));
                    }
                    if (e.key === "Backspace" && !e.metaKey) {
                      if (stagedForDelete) {
                        Common.deleteTodoAndMoveChildren(todoRelation);
                        Common.mapNullable(containerRef.current, (function (containerEl) {
                                Common.focusPreviousClass(Types.listItemClass, containerEl);
                              }));
                      } else {
                        setStagedForDelete(function (param) {
                              return true;
                            });
                      }
                    }
                    if (e.key === "Enter" && e.metaKey) {
                      makeNewTodo();
                    }
                    if (e.key === "Enter") {
                      e.preventDefault();
                      Common.mapNullable(inputRef.current, (function (inputEl) {
                              inputEl.focus();
                              inputEl.selectionStart = Caml_option.nullable_to_opt(inputEl.selectionEnd);
                            }));
                    }
                    if (e.key === "Escape") {
                      if (stagedForDelete) {
                        return setStagedForDelete(function (param) {
                                    return false;
                                  });
                      } else {
                        setSelectedElement(function (param) {
                              
                            });
                        setDisplayElement(function (param) {
                              
                            });
                        dom.blur();
                        return ;
                      }
                    }
                    
                  }));
    }
    
  };
  var onKeyDownInput = function (e) {
    setStagedForDelete(function (param) {
          return false;
        });
    Common.mapNullable(inputRef.current, (function (dom) {
            indentation(e);
            var cursorPosition = Core__Option.getOr(Caml_option.nullable_to_opt(dom.selectionStart), 0);
            var inputValueLength = dom.value.length;
            if (e.key === "ArrowUp") {
              e.stopPropagation();
              if (cursorPosition === 0) {
                e.preventDefault();
                focusContainer();
              }
              
            }
            if (e.key === "ArrowDown") {
              e.stopPropagation();
              if (cursorPosition === inputValueLength) {
                e.preventDefault();
                focusContainer();
              }
              
            }
            if (e.key === "Backspace" && inputValueLength === 0) {
              if (stagedForDelete) {
                Common.deleteTodoAndMoveChildren(todoRelation);
                Common.mapNullable(containerRef.current, (function (containerEl) {
                        Common.focusPreviousClass(Types.listItemClass, containerEl);
                      }));
              } else {
                setStagedForDelete(function (param) {
                      return true;
                    });
              }
            }
            if (e.key === "Enter" && cursorPosition === inputValueLength) {
              e.preventDefault();
              e.stopPropagation();
              makeNewTodo();
            }
            if (e.key === "Escape") {
              if (stagedForDelete) {
                return setStagedForDelete(function (param) {
                            return false;
                          });
              } else {
                setSelectedElement(function (param) {
                      
                    });
                setDisplayElement(function (param) {
                      
                    });
                dom.blur();
                return ;
              }
            }
            
          }));
  };
  var statusSelect = JsxRuntime.jsx(Common.StatusSelect.make, {
        status: todo.status,
        setStatus: (function (newStatus) {
            Common.setTodoStatus(todo.id, newStatus);
          }),
        focusTodo: (function () {
            setFocusIdNext(function (param) {
                  return Types.getTodoId(todo.id);
                });
          }),
        isOpen: match[0],
        onOpenChange: (function (v) {
            setStatusSelectIsOpen(function (param) {
                  return v;
                });
          }),
        hasHidden: todoRelation.hasHiddenChildren,
        mode: todo.mode,
        setMode: (function (m) {
            Common.setTodoMode(todo.id, m);
          }),
        date: Core__Option.map(Caml_option.nullable_to_opt(todo.target_date), (function (prim) {
                return new Date(prim);
              })),
        setDate: (function (newDate) {
            Common.setTodoDate(todo.id, Common.toNullableNull(Core__Option.map(newDate, (function (x) {
                            return FormatISO(x, {
                                        format: undefined,
                                        representation: "date"
                                      });
                          }))));
          })
      });
  var match$3 = todo.is_first_of_mode;
  var tmp;
  if (match$3 !== undefined) {
    switch (match$3) {
      case "Working" :
          tmp = null;
          break;
      case "Stashed" :
          tmp = JsxRuntime.jsxs("li", {
                children: [
                  Core__Array.make(todoRelation.depth - 1 | 0, false).map(function (param, i) {
                        return JsxRuntime.jsx("div", {
                                    className: "self-stretch w-2 ml-2 border-l border-[var(--t3)] "
                                  }, i.toString());
                      }),
                  JsxRuntime.jsx(Tb.TbBookmark, {
                        className: "w-3 ml-1.5"
                      }),
                  JsxRuntime.jsx("span", {
                        children: "Stashed",
                        className: "text-2xs ml-1.5"
                      })
                ],
                className: " text-[var(--t5)] bg-transparent flex flex-row items-center "
              });
          break;
      case "Archive" :
          tmp = JsxRuntime.jsxs("li", {
                children: [
                  Core__Array.make(todoRelation.depth - 1 | 0, false).map(function (param, i) {
                        return JsxRuntime.jsx("div", {
                                    className: "self-stretch w-2 ml-2 border-l border-[var(--t3)] "
                                  }, i.toString());
                      }),
                  JsxRuntime.jsx(Tb.TbArchive, {
                        className: "w-3 ml-1.5"
                      }),
                  JsxRuntime.jsx("span", {
                        children: "Archived",
                        className: "text-2xs ml-1.5"
                      })
                ],
                className: " text-[var(--t5)] bg-transparent flex flex-row items-center"
              });
          break;
      
    }
  } else {
    tmp = null;
  }
  return JsxRuntime.jsxs(React.Fragment, {
              children: [
                tmp,
                JsxRuntime.jsxs("li", {
                      children: [
                        props.moveActive ? JsxRuntime.jsx("div", {
                                className: "inset-0 absolute bg-amber-400 opacity-0 cursor-move z-10 drag-mask",
                                id: Types.getDragId(todo.id),
                                onMouseDown: (function (param) {
                                    setDrag();
                                  })
                              }) : null,
                        Core__Array.make(todoRelation.depth - 1 | 0, false).map(function (param, i) {
                              return JsxRuntime.jsx("div", {
                                          className: "self-stretch w-2 ml-2 border-l border-[var(--t3)] "
                                        }, i.toString());
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                statusSelect,
                                JsxRuntime.jsxs("div", {
                                      children: [
                                        JsxRuntime.jsx("div", {
                                              className: "opacity-0 absolute drag-marker -top-[5px] -left-2 z-10 h-0.5 w-full bg-amber-500",
                                              id: Types.getDropId(todo.id)
                                            }),
                                        Core__Option.isSome(todo.is_last_of_mode) ? JsxRuntime.jsx("div", {
                                                className: "opacity-0 absolute drag-marker drag-marker-bottom top-[18px] -left-2 z-10 h-0.5 w-full bg-amber-500",
                                                id: Types.getDropId(todo.id)
                                              }) : null,
                                        isSelected || isDisplayElement ? null : JsxRuntime.jsx("div", {
                                                className: "h-px w-full absolute bg-[var(--t2)] -bottom-1"
                                              }),
                                        JsxRuntime.jsx(ReactTextareaAutosize, {
                                              ref: Caml_option.some(inputRef),
                                              className: [
                                                  Types.todoInputClass,
                                                  "mx-1 block w-full h-5 border-0 pl-0 py-0 focus:ring-0  bg-transparent text-xs font-medium"
                                                ].join(" "),
                                              id: Types.getTodoInputId(todo.id),
                                              style: {
                                                resize: "none"
                                              },
                                              placeholder: todoRelation.depth === 0 ? "Untitled Project" : "",
                                              value: Core__Option.getOr(match$1[0], ""),
                                              onKeyDown: onKeyDownInput,
                                              onFocus: (function (param) {
                                                  setSelectedElement(function (param) {
                                                        return todo.id;
                                                      });
                                                  setDisplayElement(function (param) {
                                                        return todo.id;
                                                      });
                                                }),
                                              onBlur: (function (param) {
                                                  setSelectedElement(function (param) {
                                                        
                                                      });
                                                }),
                                              onChange: (function (e) {
                                                  setText(e.target.value);
                                                })
                                            }),
                                        Core__Option.isSome(Caml_option.nullable_to_opt(todo.target_date)) ? JsxRuntime.jsx(Common.DateSelect.make, {
                                                value: Core__Option.map(Caml_option.nullable_to_opt(todo.target_date), (function (prim) {
                                                        return new Date(prim);
                                                      })),
                                                onClick: (function (newDate) {
                                                    Common.setTodoDate(todo.id, Common.toNullableNull(Core__Option.map(newDate, (function (x) {
                                                                    return FormatISO(x, {
                                                                                format: undefined,
                                                                                representation: "date"
                                                                              });
                                                                  }))));
                                                  }),
                                                className: "mr-1 ml-1"
                                              }) : null,
                                        JsxRuntime.jsx(Todo$CollapseControls, {
                                              todo: todo,
                                              todoRelation: todoRelation
                                            }),
                                        props.showCheckboxes ? JsxRuntime.jsx("div", {
                                                children: JsxRuntime.jsx("input", {
                                                      className: ["border-[var(--t4)] bg-[var(--t0)] rounded text-blue-400 dark:text-blue-800 w-4 h-4 focus:ring-offset-0 focus:ring-blue-500"].join(" "),
                                                      checked: isChecked,
                                                      type: "checkbox",
                                                      onChange: (function (param) {
                                                          setChecked(function (v) {
                                                                if (Belt_SetString.has(v, todo.id)) {
                                                                  return Belt_SetString.remove(v, todo.id);
                                                                } else {
                                                                  return Belt_SetString.add(v, todo.id);
                                                                }
                                                              });
                                                        })
                                                    }),
                                                className: [" h-full pr-2 pl-1 flex flex-row items-center"].join(" ")
                                              }) : null
                                      ],
                                      className: ["relative flex-1 flex flex-row h-full justify-start items-center "].join(" ")
                                    })
                              ],
                              className: [
                                  " flex group flex-row justify-start items-center h-full flex-1 rounded-sm  py-1 pl-1",
                                  stagedForDelete ? "outline-red-700 dark:outline-red-500" : " outline-blue-500 dark:outline-blue-700",
                                  stagedForDelete ? "bg-red-200 dark:bg-red-950" : (
                                      isChecked ? "bg-sky-50 dark:bg-sky-950" : ""
                                    ),
                                  isSelected || isDisplayElement ? "outline outline-2 -outline-offset-2 " : ""
                                ].join(" ")
                            })
                      ],
                      ref: Caml_option.some(containerRef),
                      className: [
                          Types.listItemClass,
                          "relative flex flex-row justify-start items-center outline-none "
                        ].join(" "),
                      id: Types.getTodoId(todo.id),
                      tabIndex: 0,
                      onKeyDown: onKeyDownContainer,
                      onFocus: (function (param) {
                          setSelectedElement(function (param) {
                                return todo.id;
                              });
                          setDisplayElement(function (param) {
                                return todo.id;
                              });
                        }),
                      onBlur: (function (param) {
                          setSelectedElement(function (param) {
                                
                              });
                          setStagedForDelete(function (param) {
                                return false;
                              });
                        })
                    })
              ]
            });
}

var make = Todo;

export {
  TopCollapseControls ,
  CollapseControls ,
  make ,
}
/* Types Not a pure module */
