// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Types from "./Types.res.mjs";
import * as React from "react";
import * as Common from "./Common.res.mjs";
import * as Caml_obj from "rescript/lib/es6/caml_obj.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Array from "@rescript/core/src/Core__Array.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Belt_SetString from "rescript/lib/es6/belt_SetString.js";
import * as State from "@legendapp/state";
import * as JsxRuntime from "react/jsx-runtime";
import FormatISO from "date-fns/formatISO";
import ReactTextareaAutosize from "react-textarea-autosize";

function Todo(props) {
  var itemToMoveHandleMouseEnter = props.itemToMoveHandleMouseEnter;
  var setChecked = props.setChecked;
  var isChecked = props.isChecked;
  var setFocusIdNext = props.setFocusIdNext;
  var setDisplayElement = props.setDisplayElement;
  var isDisplayElement = props.isDisplayElement;
  var setSelectedElement = props.setSelectedElement;
  var isSelected = props.isSelected;
  var getTodos = props.getTodos;
  var todoRelation = props.todoRelation;
  var todo = todoRelation.self;
  var match = React.useState(function () {
        return false;
      });
  var setStatusSelectIsOpen = match[1];
  var match$1 = Common.useDebounce(Caml_option.nullable_to_opt(todo.text), (function (v) {
          Core__Option.mapOr(v, undefined, (function (v_) {
                  Common.setTodoText(todo.id, v_);
                }));
        }), 1000);
  var setText = match$1[1];
  var match$2 = React.useState(function () {
        return false;
      });
  var setStagedForDelete = match$2[1];
  var stagedForDelete = match$2[0];
  var inputRef = React.useRef(null);
  var containerRef = React.useRef(null);
  React.useEffect((function () {
          if (Caml_obj.notequal(Caml_option.nullable_to_opt(inputRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
            setText(function (param) {
                  return Caml_option.nullable_to_opt(todo.text);
                });
          }
          
        }), [todo.text]);
  var focusContainer = function () {
    Common.mapNullable(containerRef.current, (function (dom) {
            dom.focus();
          }));
  };
  var indentation = function (e) {
    if (e.key === "Tab") {
      e.preventDefault();
    }
    if (e.key === "Tab" && !e.shiftKey || e.key === "]" && e.metaKey) {
      e.preventDefault();
      State.batch(function () {
            Core__Option.mapOr(todoRelation.sibs[todoRelation.index - 1 | 0], undefined, (function (x) {
                    Core__Option.mapOr(getTodos().find(function (t) {
                              return t.self.id === x.id;
                            }), undefined, (function (prevSib) {
                            Core__Option.mapOr(prevSib.children[prevSib.children.length - 1 | 0], Common.setTodoPosition(todo.id, x.id, 1), (function (prevSibLastChild) {
                                    Common.setTodoPosition(todo.id, x.id, prevSibLastChild.position + 1);
                                  }));
                          }));
                  }));
            todoRelation.children.forEach(function (v) {
                  Common.setTodoPosition(v.id, todo.parent_todo, todo.position + v.position);
                });
          });
    }
    if ((e.key === "Tab" && e.shiftKey || e.key === "[" && e.metaKey) && !(todo.parent_todo == null)) {
      e.preventDefault();
      State.batch(function () {
            var newTodoParent = Common.toNullableNull(Core__Option.flatMap(Caml_option.nullable_to_opt(todoRelation.parent), (function (x) {
                        return Caml_option.nullable_to_opt(x.parent_todo);
                      })));
            var match = todoRelation.parent;
            var match$1 = todoRelation.tios[todoRelation.parentIndex + 1 | 0];
            var newTodoPosition = (match == null) ? (
                match$1 !== undefined ? match$1.position / 2 : 1
              ) : (
                match$1 !== undefined ? (match.position + match$1.position) / 2 : match.position + 1
              );
            Common.setTodoPosition(todo.id, newTodoParent, newTodoPosition);
            todoRelation.sibs.slice(todoRelation.index + 1 | 0).forEach(function (v) {
                  var newPosition = Core__Option.mapOr(todoRelation.children[todoRelation.children.length - 1 | 0], 0, (function (c) {
                          return c.position;
                        })) + v.position;
                  Common.setTodoPosition(v.id, todo.id, newPosition);
                });
          });
      return ;
    }
    
  };
  var makeNewTodo = function () {
    var newPosition = todoRelation.depth === 0 || todoRelation.children.length > 0 ? Core__Option.mapOr(todoRelation.children[0], 0, (function (x) {
              return x.position / 2;
            })) : Core__Option.mapOr(todoRelation.sibs[todoRelation.index + 1 | 0], todo.position + 1, (function (nextSib) {
              return (nextSib.position + todo.position) / 2;
            }));
    var newParent = todoRelation.depth === 0 || todoRelation.children.length > 0 ? todo.id : todo.parent_todo;
    var newId = Common.addTodo("", newParent, newPosition);
    setFocusIdNext(function (param) {
          return Types.getTodoInputId(newId);
        });
  };
  var onKeyDownContainer = function (e) {
    if (isSelected && Caml_obj.equal(Caml_option.nullable_to_opt(containerRef.current), Caml_option.nullable_to_opt(document.activeElement))) {
      return Common.mapNullable(containerRef.current, (function (dom) {
                    indentation(e);
                    if (e.key === "s") {
                      e.preventDefault();
                      setStatusSelectIsOpen(function (param) {
                            return true;
                          });
                    }
                    if (e.key === "ArrowUp") {
                      e.preventDefault();
                      Common.focusPreviousClass(Types.listItemClass, dom);
                    }
                    if (e.key === "ArrowDown") {
                      e.preventDefault();
                      Common.focusNextClass(Types.listItemClass, dom);
                    }
                    if (e.key === "Backspace" && e.metaKey) {
                      Common.deleteTodoAndMoveChildren(todoRelation);
                      Common.mapNullable(containerRef.current, (function (containerEl) {
                              Common.focusPreviousClass(Types.listItemClass, containerEl);
                            }));
                    }
                    if (e.key === "Backspace" && !e.metaKey) {
                      if (stagedForDelete) {
                        Common.deleteTodoAndMoveChildren(todoRelation);
                        Common.mapNullable(containerRef.current, (function (containerEl) {
                                Common.focusPreviousClass(Types.listItemClass, containerEl);
                              }));
                      } else {
                        setStagedForDelete(function (param) {
                              return true;
                            });
                      }
                    }
                    if (e.key === "Enter" && e.metaKey) {
                      makeNewTodo();
                    }
                    if (e.key === "Enter") {
                      e.preventDefault();
                      Common.mapNullable(inputRef.current, (function (inputEl) {
                              inputEl.focus();
                              inputEl.selectionStart = Caml_option.nullable_to_opt(inputEl.selectionEnd);
                            }));
                    }
                    if (e.key === "Escape") {
                      if (stagedForDelete) {
                        return setStagedForDelete(function (param) {
                                    return false;
                                  });
                      } else {
                        setSelectedElement(function (param) {
                              
                            });
                        setDisplayElement(function (param) {
                              
                            });
                        dom.blur();
                        return ;
                      }
                    }
                    
                  }));
    }
    
  };
  var onKeyDownInput = function (e) {
    setStagedForDelete(function (param) {
          return false;
        });
    Common.mapNullable(inputRef.current, (function (dom) {
            indentation(e);
            var cursorPosition = Core__Option.getOr(Caml_option.nullable_to_opt(dom.selectionStart), 0);
            var inputValueLength = dom.value.length;
            if (e.key === "ArrowUp") {
              e.stopPropagation();
              if (cursorPosition === 0) {
                e.preventDefault();
                focusContainer();
              }
              
            }
            if (e.key === "ArrowDown") {
              e.stopPropagation();
              if (cursorPosition === inputValueLength) {
                e.preventDefault();
                focusContainer();
              }
              
            }
            if (e.key === "Backspace" && inputValueLength === 0) {
              if (stagedForDelete) {
                Common.deleteTodoAndMoveChildren(todoRelation);
                Common.mapNullable(containerRef.current, (function (containerEl) {
                        Common.focusPreviousClass(Types.listItemClass, containerEl);
                      }));
              } else {
                setStagedForDelete(function (param) {
                      return true;
                    });
              }
            }
            if (e.key === "Enter" && cursorPosition === inputValueLength) {
              e.preventDefault();
              e.stopPropagation();
              return makeNewTodo();
            }
            
          }));
  };
  var statusSelect = JsxRuntime.jsx(Common.StatusSelect.make, {
        status: todo.status,
        setStatus: (function (newStatus) {
            Common.setTodoStatus(todo.id, newStatus);
          }),
        focusTodo: (function () {
            setFocusIdNext(function (param) {
                  return Types.getTodoId(todo.id);
                });
          }),
        isOpen: match[0],
        onOpenChange: (function (v) {
            if (v) {
              return setStatusSelectIsOpen(function (param) {
                          return v;
                        });
            } else {
              return setStatusSelectIsOpen(function (param) {
                          return v;
                        });
            }
          }),
        hasHidden: todoRelation.hasHiddenChildren,
        mode: todo.mode,
        setMode: (function (m) {
            Common.setTodoMode(todo.id, m);
          })
      });
  return JsxRuntime.jsxs("li", {
              children: [
                Core__Array.make(todoRelation.depth - 1 | 0, false).map(function (param, i) {
                      return JsxRuntime.jsx("div", {
                                  className: "self-stretch w-2 border-l ml-2 border-[var(--t3)] "
                                }, i.toString());
                    }),
                JsxRuntime.jsxs("div", {
                      children: [
                        todoRelation.depth > 0 ? statusSelect : null,
                        JsxRuntime.jsxs("div", {
                              children: [
                                isSelected || isDisplayElement ? null : JsxRuntime.jsx("div", {
                                        className: "h-px w-full absolute bg-[var(--t2)] -bottom-0"
                                      }),
                                JsxRuntime.jsx(ReactTextareaAutosize, {
                                      ref: Caml_option.some(inputRef),
                                      className: [
                                          Types.todoInputClass,
                                          todoRelation.depth === 0 ? "font-black" : "text-sm",
                                          "mx-1 my-1 block w-full h-5 border-0 pl-0 py-0 focus:ring-0 text-[var(--t10)] bg-transparent"
                                        ].join(" "),
                                      id: Types.getTodoInputId(todo.id),
                                      style: {
                                        resize: "none"
                                      },
                                      placeholder: todoRelation.depth === 0 ? "Untitled Project" : "",
                                      value: Core__Option.getOr(match$1[0], ""),
                                      onKeyDown: onKeyDownInput,
                                      onFocus: (function (param) {
                                          setSelectedElement(function (param) {
                                                return todo.id;
                                              });
                                          setDisplayElement(function (param) {
                                                return todo.id;
                                              });
                                        }),
                                      onBlur: (function (param) {
                                          setSelectedElement(function (param) {
                                                
                                              });
                                        }),
                                      onChange: (function (e) {
                                          setText(e.target.value);
                                        })
                                    }),
                                todoRelation.depth === 0 ? statusSelect : null,
                                todoRelation.depth === 0 ? JsxRuntime.jsx("div", {
                                        className: "w-2"
                                      }) : null,
                                Core__Option.isSome(Caml_option.nullable_to_opt(todo.target_date)) ? JsxRuntime.jsx(Common.DateSelect.make, {
                                        value: Core__Option.map(Caml_option.nullable_to_opt(todo.target_date), (function (prim) {
                                                return new Date(prim);
                                              })),
                                        onClick: (function (newDate) {
                                            Common.setTodoDate(todo.id, Common.toNullableNull(Core__Option.map(newDate, (function (x) {
                                                            return FormatISO(x, {
                                                                        format: undefined,
                                                                        representation: "date"
                                                                      });
                                                          }))));
                                          }),
                                        className: "mr-1 ml-1"
                                      }) : null,
                                props.showCheckboxes ? JsxRuntime.jsx("div", {
                                        children: JsxRuntime.jsx("input", {
                                              className: ["border-[var(--t4)] bg-[var(--t0)] rounded text-blue-400 dark:text-blue-800 w-4 h-4 focus:ring-offset-0 focus:ring-blue-500"].join(" "),
                                              checked: isChecked,
                                              type: "checkbox",
                                              onChange: (function (param) {
                                                  setChecked(function (v) {
                                                        if (Belt_SetString.has(v, todo.id)) {
                                                          return Belt_SetString.remove(v, todo.id);
                                                        } else {
                                                          return Belt_SetString.add(v, todo.id);
                                                        }
                                                      });
                                                })
                                            }),
                                        className: [" h-full pr-2 pl-1 flex flex-row items-center"].join(" ")
                                      }) : null
                              ],
                              className: ["relative flex-1 ml-1 flex flex-row h-full justify-start items-center "].join(" ")
                            })
                      ],
                      className: [
                          "pl-1 group flex flex-row justify-start items-center h-full flex-1 rounded-sm",
                          stagedForDelete ? "outline-red-700 dark:outline-red-500" : "focus-within:outline-purple-500 outline-blue-500 ",
                          stagedForDelete ? "bg-red-200 dark:bg-red-950" : (
                              isChecked ? "bg-sky-50 dark:bg-sky-950" : (
                                  isDisplayElement && !isSelected ? "bg-sky-200 dark:bg-sky-900" : ""
                                )
                            ),
                          isSelected ? "outline outline-2 -outline-offset-2 " : ""
                        ].join(" ")
                    })
              ],
              ref: Caml_option.some(containerRef),
              className: [
                  Types.listItemClass,
                  todoRelation.depth === 0 ? "" : "pl-1",
                  "group flex flex-row justify-start items-center outline-none"
                ].join(" "),
              id: Types.getTodoId(todo.id),
              tabIndex: 0,
              onKeyDown: onKeyDownContainer,
              onFocus: (function (param) {
                  setSelectedElement(function (param) {
                        return todo.id;
                      });
                  setDisplayElement(function (param) {
                        return todo.id;
                      });
                }),
              onBlur: (function (param) {
                  setSelectedElement(function (param) {
                        
                      });
                  setStagedForDelete(function (param) {
                        return false;
                      });
                }),
              onMouseEnter: (function (e) {
                  itemToMoveHandleMouseEnter(false, todo.id, e);
                })
            });
}

var make = Todo;

export {
  make ,
}
/* react Not a pure module */
