// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Fa from "react-icons/fa";
import * as Tb from "react-icons/tb";
import * as JsxRuntime from "react/jsx-runtime";

function modeCompare(mode) {
  switch (mode) {
    case "Working" :
        return 0;
    case "Stashed" :
        return 1;
    case "Archive" :
        return 2;
    
  }
}

function statusToFloat(s) {
  return [
            "Unsorted",
            "Future",
            "NowIfTime",
            "NowMustDo",
            "Underway",
            "Paused",
            "ResolveDone",
            "ResolveNo"
          ].findIndex(function (a) {
              return a === s;
            });
}

function statusIcon(s) {
  switch (s) {
    case "Unsorted" :
        return JsxRuntime.jsx("div", {});
    case "Future" :
        return JsxRuntime.jsx(Fa.FaChevronRight, {});
    case "NowIfTime" :
        return JsxRuntime.jsx(Fa.FaQuestion, {});
    case "NowMustDo" :
        return JsxRuntime.jsx(Fa.FaExclamation, {});
    case "Underway" :
        return JsxRuntime.jsx(Tb.TbPlayerPlayFilled, {});
    case "Paused" :
        return JsxRuntime.jsx(Tb.TbPlayerPauseFilled, {});
    case "ResolveDone" :
        return JsxRuntime.jsx(Fa.FaCheck, {});
    case "ResolveNo" :
        return JsxRuntime.jsx(Fa.FaTimes, {});
    
  }
}

function statusStringShort(s) {
  switch (s) {
    case "Unsorted" :
        return "";
    case "Future" :
        return "*";
    case "NowIfTime" :
        return "?";
    case "NowMustDo" :
        return "!";
    case "Underway" :
        return ">";
    case "Paused" :
        return "=";
    case "ResolveDone" :
        return "v";
    case "ResolveNo" :
        return "x";
    
  }
}

function statusString(s) {
  switch (s) {
    case "Unsorted" :
        return "";
    case "Future" :
        return "Future";
    case "NowIfTime" :
        return "If Time";
    case "NowMustDo" :
        return "Must Do";
    case "Underway" :
        return "Doing";
    case "Paused" :
        return "Paused";
    case "ResolveDone" :
        return "Done";
    case "ResolveNo" :
        return "No";
    
  }
}

function statusColor(s) {
  switch (s) {
    case "Unsorted" :
        return "var(--t2)";
    case "Future" :
        return "var(--lightBlue)";
    case "NowIfTime" :
    case "NowMustDo" :
        return "var(--lightOrange)";
    case "Underway" :
    case "Paused" :
        return "var(--lightGreen)";
    case "ResolveDone" :
    case "ResolveNo" :
        return "var(--lightPurple)";
    
  }
}

function statusColorText(s) {
  switch (s) {
    case "Unsorted" :
        return "var(--t8)";
    case "Future" :
        return "var(--darkBlue)";
    case "NowIfTime" :
    case "NowMustDo" :
        return "var(--darkOrange)";
    case "Underway" :
    case "Paused" :
        return "var(--darkGreen)";
    case "ResolveDone" :
    case "ResolveNo" :
        return "var(--darkPurple)";
    
  }
}

function getTodoId(s) {
  return "todo-" + s;
}

function getTodoInputId(s) {
  return "todo-input-" + s;
}

function getIdFromId(s) {
  if (s.includes("todo-")) {
    return Core__Option.map(s.split("todo-")[1], (function (v) {
                  return v;
                }));
  } else if (s.includes("project-")) {
    return Core__Option.map(s.split("project-")[1], (function (v) {
                  return v;
                }));
  } else {
    return ;
  }
}

var SMap;

var SSet;

var listItemClass = "class-list-item";

var todoInputClass = "class-list-todo-input";

export {
  SMap ,
  SSet ,
  modeCompare ,
  statusToFloat ,
  statusIcon ,
  statusStringShort ,
  statusString ,
  statusColor ,
  statusColorText ,
  getTodoId ,
  getTodoInputId ,
  getIdFromId ,
  listItemClass ,
  todoInputClass ,
}
/* react-icons/fa Not a pure module */
