// Generated by ReScript, PLEASE EDIT WITH CARE


function isArchiveStatus(s) {
  switch (s) {
    case "ArchiveDone" :
    case "ArchiveReject" :
    case "ArchiveNoNeed" :
        return true;
    default:
      return false;
  }
}

function statusToFloat(s) {
  switch (s) {
    case "TodoUrgent" :
        return 0;
    case "TodoHigh" :
        return 1;
    case "TodoMedium" :
        return 2;
    case "TodoLow" :
        return 3;
    case "LaterWill" :
        return 4;
    case "LaterMaybe" :
        return 5;
    case "LaterUnlikely" :
        return 6;
    case "LaterUnsorted" :
        return 7;
    case "ResolveDone" :
        return 8;
    case "ResolveReject" :
        return 9;
    case "ResolveNoNeed" :
        return 10;
    case "ArchiveDone" :
        return 11;
    case "ArchiveReject" :
        return 12;
    case "ArchiveNoNeed" :
        return 13;
    case "Trash" :
        return 14;
    
  }
}

function statusString(s) {
  switch (s) {
    case "TodoUrgent" :
        return "Urgent";
    case "TodoHigh" :
        return "High";
    case "TodoMedium" :
        return "Medium";
    case "TodoLow" :
        return "Low";
    case "LaterWill" :
        return "Will Do";
    case "LaterMaybe" :
        return "Maybe";
    case "LaterUnlikely" :
        return "Unlikely";
    case "LaterUnsorted" :
        return "Unsorted";
    case "ResolveDone" :
    case "ArchiveDone" :
        return "Done";
    case "ResolveReject" :
    case "ArchiveReject" :
        return "Reject";
    case "ResolveNoNeed" :
    case "ArchiveNoNeed" :
        return "No Need";
    case "Trash" :
        return "Delete";
    
  }
}

function statusStringShort(s) {
  switch (s) {
    case "TodoUrgent" :
        return "!";
    case "TodoHigh" :
        return "1";
    case "TodoMedium" :
        return "2";
    case "TodoLow" :
        return "3";
    case "LaterWill" :
        return "A";
    case "LaterMaybe" :
        return "B";
    case "LaterUnlikely" :
        return "C";
    case "LaterUnsorted" :
        return "-";
    case "ResolveDone" :
    case "ArchiveDone" :
        return "✔︎";
    case "ResolveReject" :
    case "ArchiveReject" :
        return "🞫";
    case "ResolveNoNeed" :
    case "ArchiveNoNeed" :
        return "○";
    case "Trash" :
        return "D";
    
  }
}

export {
  isArchiveStatus ,
  statusToFloat ,
  statusString ,
  statusStringShort ,
}
/* No side effect */
