create table projects (
    id uuid default gen_random_uuid() primary key,
    counter bigint generated by default as identity,
    name text,
    created_at timestamptz default now(),
    updated_at timestamptz default now(),
    deleted boolean default false -- needed for soft deletes
);

alter table todos add column project uuid references projects (id);
alter table todos add column parent_todo uuid references todos (id);
alter table todos add column position decimal;
alter table todos add column user_id uuid references auth.users (id);
alter table projects add column user_id uuid references auth.users (id);

drop trigger handle_times on todos;

create trigger handle_times_todos
before insert or update on todos
for each row
execute procedure handle_times();


create trigger handle_times_projects
before insert or update on projects
for each row
execute procedure handle_times();
